name       : python-orjson
version    : 3.8.2
release    : 19
source     :
    - https://github.com/ijl/orjson/archive/3.8.2.tar.gz : a2fd34e366e7b9cde45cd59a1a97ec9cacbfd8c28f4fa75adbf37b824c6db40e
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --cargo-extra-args="--features=yyjson" --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
