name       : python-orjson
version    : 3.7.8
release    : 12
source     :
    - https://github.com/ijl/orjson/archive/3.7.8.tar.gz : 6ad913aa0490b6db67ebd6879cbef57f90a84c1fe611454aeaa99afa03dc8213
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --cargo-extra-args="--features=yyjson" --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
