name       : python-orjson
version    : 3.6.7
release    : 4
source     :
    - https://github.com/ijl/orjson/archive/3.6.7.tar.gz : 138f952a19f0fff525f470f7d1d492945aba6ee70363b906b9394366a228ed98
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
builddeps  :
    - cargo
    - python-maturin
build      : |
    maturin build --no-sdist --release --strip --manylinux off
install    : |
    pip3 install --isolated --root=$installdir --ignore-installed --no-deps $workdir/target/wheels/*
