name       : python-orjson
version    : 3.7.12
release    : 16
source     :
    - https://github.com/ijl/orjson/archive/3.7.12.tar.gz : 9ca880da6b2092425c9b563173fd970192f1f0c5b254d48aaca6d8b51d4a2077
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --cargo-extra-args="--features=yyjson" --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
