name       : python-orjson
version    : 3.6.9
release    : 7
source     :
    - https://github.com/ijl/orjson/archive/3.6.9.tar.gz : f0300640834f67678d511193958da48dc324297c12c0a640dd26ef9b997cec13
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
