name       : python-orjson
version    : 3.8.13
release    : 26
source     :
    - https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.8.13.tar.gz : 14e54713703d5436a7be54ff50d780b6b09358f1a0be6107a3ea4f3537a4f6d8
license    :
    - Apache-2.0
    - MIT
component  : programming.python
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - numpy #check
    - python-arrow #check
    - python-installer
    - python-maturin
    - python-psutil #check
    - python-pytest #check
    - python-pytz #check
    - python-tomli
build      : |
    maturin build --release --strip --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
check      : |
    %python3_test pytest3
