name       : python-orjson
version    : 3.7.6
release    : 10
source     :
    - https://github.com/ijl/orjson/archive/3.7.6.tar.gz : 8ad1789faa02b64d767f7e8dbee3b128c888ba22165de0b85a6044ecd8284218
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --cargo-extra-args="--features=yyjson" --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
