name       : python-orjson
version    : 3.7.9
release    : 13
source     :
    - https://github.com/ijl/orjson/archive/3.7.9.tar.gz : 59420de9aef8fbc05193c124acddaee458587edb68c23e8904fe900f8fbb651f
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --cargo-extra-args="--features=yyjson" --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
