name       : python-orjson
version    : 3.6.5
release    : 2
source     :
    - https://github.com/ijl/orjson/archive/3.6.4.tar.gz : 5a424e8a2bf353a057d8903ccdda49d112b139277678a560e5a4b3581852584d
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
builddeps  :
    - cargo
    - python-maturin
build      : |
    maturin build --no-sdist --release --strip --manylinux off
install    : |
    pip3 install --isolated --root=$installdir --ignore-installed --no-deps $workdir/target/wheels/*
