name       : python-orjson
version    : 3.6.8
release    : 5
source     :
    - https://github.com/ijl/orjson/archive/3.6.8.tar.gz : a8b44549ea2cfec0a0f18a90a8641fb5d4e41941502d646a40922622d8bb559f
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
builddeps  :
    - cargo
    - python-maturin
build      : |
    maturin build --no-sdist --release --strip --manylinux off
install    : |
    pip3 install --isolated --root=$installdir --ignore-installed --no-deps $workdir/target/wheels/*
