name       : python-orjson
version    : 3.8.3
release    : 20
source     :
    - https://github.com/ijl/orjson/archive/3.8.3.tar.gz : 2e93c9f43a29a60096b182be8b5f1b89d9f9c8e2887f1d8080ee7800a373dc93
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - python-installer
    - python-maturin
    - python-tomli
build      : |
    maturin build --no-sdist --release --strip --cargo-extra-args="--features=yyjson" --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
