name       : python-orjson
version    : 3.8.11
release    : 23
source     :
    - https://github.com/ijl/orjson/archive/3.8.11.tar.gz : db42423770f9c22f3efc38371379aa332f38a3a0be036f99bebca131c2bf8e1b
license    :
    - Apache-2.0
    - MIT
component  : programming.python
networking : yes
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - numpy #check
    - python-arrow #check
    - python-installer
    - python-maturin
    - python-psutil #check
    - python-pytest #check
    - python-pytz #check
    - python-tomli
build      : |
    maturin build --release --strip --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
check      : |
    %python3_test pytest3
